1. Numpy

In [133]:
import numpy as np

In [134]:
data = [[1,2,3], [4,5,6], [7,8,9]]
a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [135]:
a.dtype

dtype('int32')

In [136]:
a = a.astype(np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [137]:
# 3x3 = 9 수를 맞추어주셔야됩니다
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
# 3x4 = 12 수를 맞추어주었습니다
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [139]:
np.arange(1,13).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [140]:
np.nan * 10

nan

In [141]:
a[0][1] = np.nan

In [142]:
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [143]:
a  = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
#정수형에서는 결측값 부여할 수 없다 -> 오류가 발생
a[0][1] = np.nan

ValueError: cannot convert float NaN to integer

In [ ]:
# linspace 끝은 최종값을 의미하는 것이 아니라 생성개수를 의마한다
a = np.linspace(1,10,10)
a

In [ ]:
a = np.linspace(1,10,20)
a

연산

In [ ]:
data = np.arange(1,10).reshape(3,3)
data

In [ ]:
data + data

In [ ]:
[1,2,3] + [4,5,6]

In [ ]:
data - data

In [ ]:
data * data

In [ ]:
data / data

In [ ]:
np.dot(data, data)

In [ ]:
data@data

차원

In [ ]:
#0차원 : 스칼라
a = np.array(1)
a
a.shape

In [ ]:
#차원을 의미
a.ndim

In [ ]:
#1차원 : 벡터
a = np.array([1,2,3,4,5])
a
a.shape

In [ ]:
a.ndim

In [ ]:
#2차원 : 메트릭스
a = np.array([[1,2,3],[4,5,6]])
a
a.shape

In [ ]:
a.ndim

In [ ]:
#2차원 : 메트릭스
a = np.array([[1]])
a
a.shape

In [ ]:
a.ndim

In [ ]:
#3차원 : 3차원 이상의 다차원의 행렬을 Tensor
a = np.array([[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]])
a
a.shape

matrix의 유형

In [ ]:
a = np.arange(12).reshape(2,3,2)
a

In [ ]:
#1차원행렬을 1로채움
b = np.ones(12)
b

In [ ]:
#2x3x2를 0으로 채웠다
b = np.zeros(12).reshape(2,3,2)
b

In [ ]:
#단위행렬을 만들어줌(곱하였을때 자기자신으로 만들어주는 행렬)
d = np.eye(3)
d

In [ ]:
#3x4를 0으로 채워줌
e = np.zeros([3,4])
e

In [ ]:
#3x4x2 를 0으로 채워줌
e = np.zeros([3,4,2])
e

In [ ]:
#값을 채워줌
f = np.empty([2,3])
f

In [ ]:
#3x4 2차원행렬을 1000으로 채움
g = np.full((3,4), 1000)
g

In [ ]:
#2와 10사이의 값들을 같은 간격으로 6개로 나눔
h = np.linspace(2,10,6)
h

잡계 함수

In [ ]:
a = np.arange(10).reshape(2,5)
a

In [ ]:
a[0][0] = 100
a

In [ ]:
a[0,1] = 1000
a

In [ ]:
#평균값
np.mean(a)

In [ ]:
#중앙값
np.median(a)

In [ ]:
#표준편차값
np.std(a)

In [ ]:
#분산
np.var(a)

In [ ]:
#합
np.sum(a)

In [145]:
sum(a)

array([12, 15, 18])

In [146]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
#axis=0 행끼리의 합
np.sum(a, axis=0)

array([12, 15, 18])

In [148]:
#axis=1 얄끼리의 합
np.sum(a, axis=1)

array([ 6, 15, 24])

In [149]:
#최댓값
np.max(a)

9

In [150]:
#최솟값
np.min(a)

1

Pandas

In [151]:
import pandas as pd
import numpy as np

In [152]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [153]:
#시리즈를 생성
a = pd.Series(data, index=['a', 'b', 'c', 'd', 'e'])
a

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [154]:
#0부터 10단위로 40까지 데이터셋 생성
data = np.arange(0, 50, 10)
data

array([ 0, 10, 20, 30, 40])

In [155]:
b = pd.Series(data)
b

0     0
1    10
2    20
3    30
4    40
dtype: int32

In [156]:
a['b']

1

In [157]:
a.loc['b']

1

In [158]:
a.iloc[1]

1

산술연산

In [159]:
a

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [160]:
a + 10

a    10
b    11
c    12
d    13
e    14
dtype: int32

In [161]:
a - 10

a   -10
b    -9
c    -8
d    -7
e    -6
dtype: int32

In [162]:
a * 10

a     0
b    10
c    20
d    30
e    40
dtype: int32

In [163]:
a ** 2

a     0
b     1
c     4
d     9
e    16
dtype: int32

In [164]:
a / 5

a    0.0
b    0.2
c    0.4
d    0.6
e    0.8
dtype: float64

In [165]:
a

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [166]:
a > 15

a    False
b    False
c    False
d    False
e    False
dtype: bool

집계함수

In [167]:
#더하기
a.add(100)

a    100
b    101
c    102
d    103
e    104
dtype: int32

In [168]:
#빼기
a.sub(100)

a   -100
b    -99
c    -98
d    -97
e    -96
dtype: int32

In [169]:
#곱셈
a.mul(100)

a      0
b    100
c    200
d    300
e    400
dtype: int32

In [170]:
#나누기
a.div(100)

a    0.00
b    0.01
c    0.02
d    0.03
e    0.04
dtype: float64

In [171]:
#최소
a.min()

0

In [172]:
#최대
a.max()

4

In [173]:
#합
a.sum()

10

In [174]:
#퍙균
a.mean()

2.0

In [175]:
#중앙값
a.median()

2.0

In [176]:
#표준편차
a.std()

1.5811388300841898

In [177]:
#븐산
a.var()

2.5

DataFrame

In [178]:
rawData = np.random.randint(50, 100, size=(4,3))
rawData

array([[99, 78, 59],
       [80, 54, 73],
       [69, 85, 70],
       [56, 78, 93]])

In [179]:
df = pd.DataFrame(rawData, 
                 index=['1반', '2반', '1반', '2반'],
                 columns=['국', '영', '수'])
df

국   영   수
1반  99  78  59
2반  80  54  73
1반  69  85  70
2반  56  78  93

In [180]:
#df[0] -> Error
df['국']

1반    99
2반    80
1반    69
2반    56
Name: 국, dtype: int32

In [181]:
df['평균'] = round((df['국'] + df['영'] + df['수'])/3, 2)
df

국   영   수     평균
1반  99  78  59  78.67
2반  80  54  73  69.00
1반  69  85  70  74.67
2반  56  78  93  75.67

In [182]:
df['na'] = np.nan
df

국   영   수     평균  na
1반  99  78  59  78.67 NaN
2반  80  54  73  69.00 NaN
1반  69  85  70  74.67 NaN
2반  56  78  93  75.67 NaN

In [183]:
del df['na']
df

국   영   수     평균
1반  99  78  59  78.67
2반  80  54  73  69.00
1반  69  85  70  74.67
2반  56  78  93  75.67

In [184]:
df[df.평균 > 75]

국   영   수     평균
1반  99  78  59  78.67
2반  56  78  93  75.67

In [185]:
#평균 컬럼 삭제 -> dropna
df = df.drop(['평균'], axis='columns')
df

국   영   수
1반  99  78  59
2반  80  54  73
1반  69  85  70
2반  56  78  93

 결측값 처리

In [186]:
#정수형에서는 결측값을 넣으면 오류가 나기에 실수형으로 변경작업
df = df.astype('float')
df

국     영     수
1반  99.0  78.0  59.0
2반  80.0  54.0  73.0
1반  69.0  85.0  70.0
2반  56.0  78.0  93.0

In [187]:
#df['수'][2]위치에 결측값 넣기
df['수'][2] = np.nan
df

국     영     수
1반  99.0  78.0  59.0
2반  80.0  54.0  73.0
1반  69.0  85.0   NaN
2반  56.0  78.0  93.0

In [188]:
df.dropna(axis=0) 

국     영     수
1반  99.0  78.0  59.0
2반  80.0  54.0  73.0
2반  56.0  78.0  93.0

In [189]:
df

국     영     수
1반  99.0  78.0  59.0
2반  80.0  54.0  73.0
1반  69.0  85.0   NaN
2반  56.0  78.0  93.0

In [190]:
df.dropna(axis=0, inplace=True) 

In [191]:
df

국     영     수
1반  99.0  78.0  59.0
2반  80.0  54.0  73.0
2반  56.0  78.0  93.0

In [192]:
df.dropna(axis=1)

국     영     수
1반  99.0  78.0  59.0
2반  80.0  54.0  73.0
2반  56.0  78.0  93.0

In [193]:
#결측치 채우기
df.fillna(0)

국     영     수
1반  99.0  78.0  59.0
2반  80.0  54.0  73.0
2반  56.0  78.0  93.0

MultiIndex

In [196]:
df

국     영     수
1반  99.0  78.0  59.0
2반  80.0  54.0  73.0
2반  56.0  78.0  93.0

In [197]:
df.T

1반    2반    2반
국  99.0  80.0  56.0
영  78.0  54.0  78.0
수  59.0  73.0  93.0

In [199]:
df.index = [['1학년', '1학년', '2학년'], ['1반', '2반', '1반']]
df

국     영     수
1학년 1반  99.0  78.0  59.0
    2반  80.0  54.0  73.0
2학년 1반  56.0  78.0  93.0

In [200]:
df.columns = [['언어', '언어', '수리'], ['국', '영', '수']]
df

언어          수리
           국     영     수
1학년 1반  99.0  78.0  59.0
    2반  80.0  54.0  73.0
2학년 1반  56.0  78.0  93.0

In [201]:
df['언어']

국     영
1학년 1반  99.0  78.0
    2반  80.0  54.0
2학년 1반  56.0  78.0

In [202]:
df.iloc[0]

언어  국    99.0
    영    78.0
수리  수    59.0
Name: (1학년, 1반), dtype: float64

데이터 사전 분석

In [204]:
df

언어          수리
           국     영     수
1학년 1반  99.0  78.0  59.0
    2반  80.0  54.0  73.0
2학년 1반  56.0  78.0  93.0

In [205]:
#정보 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 3 entries, ('1학년', '1반') to ('2학년', '1반')
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   (언어, 국)  3 non-null      float64
 1   (언어, 영)  3 non-null      float64
 2   (수리, 수)  3 non-null      float64
dtypes: float64(3)
memory usage: 142.0+ bytes


In [206]:
#위에서 5줄 출력
df.head()

언어          수리
           국     영     수
1학년 1반  99.0  78.0  59.0
    2반  80.0  54.0  73.0
2학년 1반  56.0  78.0  93.0

In [208]:
#아래서 5줄 출력
df.tail()

언어          수리
           국     영     수
1학년 1반  99.0  78.0  59.0
    2반  80.0  54.0  73.0
2학년 1반  56.0  78.0  93.0

In [210]:
#요약 출력
df.describe()

언어                    수리
               국          영          수
count   3.000000   3.000000   3.000000
mean   78.333333  70.000000  75.000000
std    21.548395  13.856406  17.088007
min    56.000000  54.000000  59.000000
25%    68.000000  66.000000  66.000000
50%    80.000000  78.000000  73.000000
75%    89.500000  78.000000  83.000000
max    99.000000  78.000000  93.000000

In [211]:
#결측치 확인
df.isnull()

언어            수리
            국      영      수
1학년 1반  False  False  False
    2반  False  False  False
2학년 1반  False  False  False

값의 연결

In [213]:
a = pd.DataFrame(np.arange(1,10).reshape(3,3))
a

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [214]:
b = pd.Series(np.arange(10,40,10))
b

0    10
1    20
2    30
dtype: int32

In [218]:
#칼람추가 concat
#ignore_index = True -> 인덱스 연결
pd.concat([a,b], axis = 1, ignore_index=True)

0  1  2   3
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [216]:
#열추가
a.append(b, ignore_index=True)

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  20  30